### ISSUE TITLE
 Authorization error (incorrect password) при правильных данных

### ISSUE THREAD

**Issue by LuceArs** [prawn-cake/vk-requests#7]
Данная проблема встречается и в других найденных vk-врапперах на пайтоне. 
Код:
```
api = vk_requests.create_api(login=login, password=password, app_id=app_id, scope="messages")
print api.users.get(user_ids=1)
```
До этого только ввод логина, пароля и номер приложения. При заходе с этими же данными через браузер, появляется капча, после ввода которой происходит успешный вход.
Логи:
`2016-03-03 14:02:08,362 INFO [vk-requests] Getting access token for user '89602314094'
2016-03-03 14:02:08,365 INFO [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): m.vk.com
2016-03-03 14:02:08,801 INFO [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): login.vk.com
2016-03-03 14:02:09,058 INFO [vk-requests] Captcha is needed
2016-03-03 14:02:09,061 INFO [vk-requests] Captcha url https://m.vk.com/captcha.php?s=0&sid=279880241682
2016-03-03 14:02:09,168 ERROR [vk-requests] Authorization error (incorrect password)
Traceback (most recent call last):
  File "C:/Users/Administrator/Documents/PycharmProjects/vk_reconnect_bot/main.py", line 7, in <module>
    api = vk_requests.create_api(login=login, password=password, app_id=app_id, scope="messages")
  File "C:\Anaconda2\lib\site-packages\vk_requests\__init__.py", line 31, in create_api
    scope=scope, api_version=api_version)
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 366, in __init__
    **api_kwargs)
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 390, in get_auth_api
    **api_kwargs)
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 49, in __init__
    self.renew_access_token()
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 79, in renew_access_token
    self._access_token = self.get_access_token()
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 121, in get_access_token
    self.do_login(session=s)
  File "C:\Anaconda2\lib\site-packages\vk_requests\auth.py", line 173, in do_login
    raise VkAuthError(message)
vk_requests.exceptions.VkAuthError: Authorization error (incorrect password)`

**Comment by LuceArs** [comment]
Прошу прощения, не обратил внимания на interactiveVKSession.

**Comment by prawn-cake** [comment]
Случай с капчей обрабатывается только в ручном / интерактивном режиме, как правило достаточно один раз разрешить этот конфликт вручную, чтобы сервис перестал блокировать автоматический вход, за исключением некоторых случаев.

Да [InteractiveVKSession](https://github.com/prawn-cake/vk-requests#interactive-session) помогает разрешить эту проблему

**Comment by LuceArs** [comment]
Как ни странно, стало работать только в режиме дебага PyCharm без какой-либо капчи. При обычной работе зависает после return user_login.strip() в auth.py

**Comment by prawn-cake** [comment]
Перепроверил интерактивную сессию, там действительно были проблемы, но в моем случае об этом явно сообщалось ошибкой. Проблема была с токеном.
Исправлено в [v0.9.3](https://github.com/prawn-cake/vk-requests/tree/0.9.3)
